# notes:
# - 'reboot' crashes qemu, https://gitlab.com/qemu-project/qemu/-/issues/1641

machine: pc
image: "./img/xp.img"
size: "32G"
cpus: 4
memory: "2G"

audio: ac97
network: legacy

current_stage: bootstrap
stages:
  bootstrap:
    isos:
    - "./iso/en_windows_xp_professional_with_service_pack_3_x86_cd_vl_x14-73974.iso" # https://massgrave.dev/windows_xp_links
